peft_model:
  id: angnami/news-mistral-7B-lora:1.0.0 
model:
  id: mistralai/Mistral-7B-Instruct-v0.2
  template_name: "mistral"
  max_new_tokens: 500
  temperature: 1.0
setup:
  device: cuda:0
  debug: False
dataset:
  file: "testing_data.json"